
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import Transition from "./component/Transition";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated By Create Next App",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
    
      <body className={inter.className} >
      <Navbar/>
      <Transition>{children}</Transition>
  
      <Footer/>
      </body>
    </html>
  );
}
